{% set name = "numcodecs" %}
{% set version = "0.4.0" %}
{% set sha256 = "2fa711722d16b89dbfe395c2aa21770994e6955c23af23c4d8536a6b61ac16e1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - export DISABLE_NUMCODECS_AVX2=""  # [unix]
    - set DISABLE_NUMCODECS_AVX2=""  # [win]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - cython
    - setuptools
    - setuptools_scm
  run:
    - python
    - numpy
    - msgpack-python
    - backports.lzma  # [py27 and unix]

test:
  requires:
    - nose
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - nosetests -v numcodecs

about:
  home: https://github.com/alimanfoo/numcodecs
  license: MIT
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.

extra:
  recipe-maintainers:
    - alimanfoo
