{% set name = "numcodecs" %}
{% set version = "0.16.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 53d705865faaf0a7927c973af3777532001c8fbb653de119c1e844608614d799
  patches:
    - patches/0001-Unvendor-deps.patch

build:
  number: 0
  skip: true  # [py<311]
  script:
    - export DISABLE_NUMCODECS_AVX2=""  # [unix]
    - export DISABLE_NUMCODECS_SSE2=""  # [osx and arm64]
    - set DISABLE_NUMCODECS_AVX2=""  # [win]
    - {{ PYTHON }} -m pip install --no-deps . -vv --no-build-isolation

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - toml
    - py-cpuinfo
    - setuptools >=77
    - setuptools-scm >=6.2
    - numpy {{ numpy }}
    - blosc {{ blosc }}
    - lz4-c {{ lz4_c }}
    - zstd {{ zstd }}
  run:
    - python
    # numcodecs/__init__.py requires msgpack,
    # see https://github.com/zarr-developers/numcodecs/blob/v0.16.3/numcodecs/__init__.py#L134
    - msgpack-python
    - numpy >=1.24
    # bounds set through run_exports
    - blosc
    - lz4-c
    - zstd
    - typing_extensions
  run_constrained:
    - crc32c >=2.7
    - pcodec >=0.3,<0.4
    - zfpy >=1.0.0

test:
  requires:
    - pytest
    - importlib_metadata
    - pip
    - pyzstd
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v --pyargs numcodecs

about:
  home: https://github.com/zarr-developers/numcodecs
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.
  description: |
    Numcodecs is a Python package providing buffer compression and transformation codecs for use in data storage and communication applications. These include:
    Compression codecs, e.g., Zlib, BZ2, LZMA, ZFPY and Blosc.
    Pre-compression filters, e.g., Delta, Quantize, FixedScaleOffset, PackBits, Categorize.
    Integrity checks, e.g., CRC32, Adler32.
    All codecs implement the same API, allowing codecs to be organized into pipelines in a variety of ways.
  dev_url: https://github.com/zarr-developers/numcodecs
  doc_url: https://numcodecs.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jrbourbeau
