{% set name = "numcodecs" %}
{% set version = "0.5.2" %}
{% set sha256 = "4c71d09ea34196f6f5a0e2091a7f41a7a5964a0bb4cbcbec8b92049c8799b417" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - export DISABLE_NUMCODECS_AVX2=""  # [unix]
    - set DISABLE_NUMCODECS_AVX2=""  # [win]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - cython
    - setuptools
    - setuptools_scm
  run:
    - python
    - numpy
    - msgpack-python
    - backports.lzma  # [py27]

test:
  requires:
    - nose
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - nosetests -v numcodecs

about:
  home: https://github.com/alimanfoo/numcodecs
  license: MIT
  license_file: LICENSE
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.

extra:
  recipe-maintainers:
    - alimanfoo
