{% set name = "numcodecs" %}
{% set version = "0.10.2" %}
{% set sha256 = "22838c6b3fd986bd9c724039b88870057f790e22b20e6e1cbbaa0de142dd59c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - export DISABLE_NUMCODECS_AVX2=""  # [unix]
    - export DISABLE_NUMCODECS_SSE2=""  # [arm64]
    - set DISABLE_NUMCODECS_AVX2=""  # [win]
    - {{ PYTHON }} -m pip install . -vv
  # numcodecs is not currently supported on s390x
  skip: true  # [py<36 or s390x]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools >18.0
    - setuptools_scm >1.5.4
    - wheel
  run:
    - python
    - numpy >=1.7
    - msgpack-python

test:
  requires:
    - pytest
    - pip
  imports:
    - numcodecs
    - numcodecs.blosc
    - numcodecs.lz4
    - numcodecs.zstd
  commands:
    - pip check
    - pytest -v --pyargs numcodecs

about:
  home: https://github.com/zarr-developers/numcodecs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package providing buffer compression and transformation codecs for use in data storage and communication applications.
  dev_url: https://github.com/zarr-developers/numcodecs
  doc_url: https://numcodecs.readthedocs.io/en/stable/
  
extra:
  recipe-maintainers:
    - alimanfoo
    - jakirkham
    - jrbourbeau
