travis:
  secure:
    BINSTAR_TOKEN: K2fxAPbrcWCFOKQ9VTA+aLUyugqW+7nvI6AP4mEvf4SJkiyjgLP4dnfECeGEkoRTKIDYhnM9BkVOFigJ6vTxrjImRhWUn+sL4jB/kB8yp6QjXSm8YZHIBCAYwlKfftKYzqsjgoOGcvDP+cDbU8FOoupqy2Mi9JUbfQ3HmNq3uWi0wis1G+oWyWS3m3mP1n3a7udeLrPvxKIQCH7tofD1h0VA3Iza+DMkNw4dx0/CfmAAGBA7eOG43Z9igz+bu3Kt4gyU2NwBUfaes8KmsWNLbX7dU76leKkDi0edj6R2sQxQLRcTsSnkmTKdtVG0O2l0t7am9ucURNwdIeWle3Oo6q3AmIwIDKJUxxIvj1OZjrgQcX9rnETVmKP/KkkX0wRAhiHcCpUL/CiH2oMKQ4Jsh76imWrKUuXf+CcgOpHB6qCyNEkIGDYmcyUhRPPPukDBngDI00ltaW169Lbf/qwnFQRIB6kg9R3ELvy7OazCWM3slyiXVP+GtiZYkNKSSKWbQEltbf6JEcQ3KXk88WdgApZpdTtGU8rqgiv6BIAKm0l1x/WiN53/2B9qAtvvTur/xrzxTNq0aUFO/JGC43nASzJZFuCHLn6coETYhXoEAOjXR4EOdjUgrsCMBjrilno1d9j7M/R4XXT9USf/wqQGgXi/1Z3d2+xNOIQSoZX5y7o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
