travis:
  secure:
    BINSTAR_TOKEN: jJwRWB/67OW2O+7DZo1sw71SKI328B5i4O8iPjzd+PEnZt1+kO7L6cvT5kmSlcnaZeGtWX2hdabgzyGdTJcjgC7qswC1lEJ9N6h/5/5BKeM4l35LDsb51Z8fmlitZzrdH8A1hrKWIcpHecInBtFeFJI8gjLoAaOTVz/ULZ0+l2UgSmLUzVqEFKhBBs3FVVzvs6HCvrYJnb4nzyWgtzoQZc4Ajp6nPfv7myATLBHov2FhwjfgYRcj31RV/nZrDs5hlGJeNRniXDx4OpTaA7cGAT/HNF2v3yoFuYmmx/foPrTK1C2ZCfnpyF7/0utayQ/R9yY5hutPKEKmEV8SwMcOQSYGcPRVOgNCsViFND8yJm4JZGx/5wb6wFYx8mbJZNi3pr82/4fcJMNNVpY8OuJeQX8wQqpXXvwCSN5oAwYkD5jUohVQGlutkb+/nBOdNikaiA8pz/PVWGtpdFHMFfYNDGWBml65L4+FDwaqZUQAJAtJc5ENqtBl93uAvMb/iGfktSmB9PYbzQDS1bAtjhU9/4cRV/CRgdMiwJt1iFoiSLDhetxVvJbMr3o4MmFZwLssj489oU1uuzUAH/HcqRmoiG7n0FMFshfvXA2muhLAQU5tDpn2fjSziQumORgoiuj+cf9wWElNIedzZQ9WtIp0TVcZYcHlXEv8SadycPybB28=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
